services:
  - type: web
    name: gm-cozil-pcm
    env: node
    buildCommand: npm install && npm run build:clean || npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

