services:
  - type: web
    name: gm-cozil-pcm
    env: node
    buildCommand: npm install && NODE_ENV=production npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

