services:
  - type: web
    name: gm-cozil-pcm
    env: node
    buildCommand: npm install && rm -rf build node_modules/.cache .cache webpack-cache && WEBPACK_CACHE_DISABLED=true npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

